######################################################################
# Automatically generated by qmake (3.0) Wed Feb 15 12:14:52 2017
######################################################################

TEMPLATE = app
TARGET = FormLayout
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
