######################################################################
# Automatically generated by qmake (3.0) Wed Feb 15 11:20:45 2017
######################################################################

TEMPLATE = app
TARGET = SignalMapper
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += MyDlg.h
SOURCES += main.cpp MyDlg.cpp
