######################################################################
# Automatically generated by qmake (3.0) Wed Feb 15 14:31:21 2017
######################################################################

TEMPLATE = app
TARGET = File
INCLUDEPATH += .

# Input
HEADERS += File.h
SOURCES += File.cpp main.cpp
