######################################################################
# Automatically generated by qmake (3.0) Wed Feb 15 13:08:12 2017
######################################################################

TEMPLATE = app
TARGET = Mutex
INCLUDEPATH += .

# Input
HEADERS += Thread.h
SOURCES += main.cpp Thread.cpp
