######################################################################
# Automatically generated by qmake (3.0) Wed Feb 15 17:03:50 2017
######################################################################

TEMPLATE = app
TARGET = CLISignalAndSlots
INCLUDEPATH += .

# Input
HEADERS += MyClass.h
SOURCES += main.cpp MyClass.cpp
