#####################################################################
# Automatically generated by qmake (3.0) Wed Feb 15 16:28:17 2017
######################################################################

TEMPLATE = app
TARGET = FileExplorer
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += FileExplorerDlg.h
SOURCES += FileExplorerDlg.cpp main.cpp
