######################################################################
# Automatically generated by qmake (3.0) Wed Feb 15 15:04:12 2017
######################################################################

TEMPLATE = app
TARGET = Semaphore
INCLUDEPATH += .

# Input
HEADERS += Thread.h
SOURCES += main.cpp Thread.cpp
